/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package removepdfpages;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;

/**
 *
 * @author Spencer
 */
public class RemovePDFPages extends javax.swing.JFrame {
    
    private JFileChooser loadChooser;
    private JFileChooser saveChooser;
    private PDDocument outFile;
    private PDDocument inFile;
    private String logString;
    private ArrayList<Integer> delPages;

    /**
     * Creates new form RemovePDFPages
     */
    public RemovePDFPages() {
        initComponents();
        
        loadChooser = new JFileChooser();
        loadChooser.setCurrentDirectory(new File("C:\\temp"));
        loadChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        loadChooser.setFileFilter(new FileNameExtensionFilter("PDF files", "pdf"));
        
        saveChooser = new JFileChooser();
        saveChooser.setCurrentDirectory(new File("C:\\temp"));
        saveChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        inFile = null;
        outFile = null;
        logString = "";
        delPages = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectFileButton.setText("Select file...");
        selectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectFileButton)
                .addContainerGap(584, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectFileButton)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
        loadFile();
    }//GEN-LAST:event_selectFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemovePDFPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemovePDFPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemovePDFPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemovePDFPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemovePDFPages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton selectFileButton;
    // End of variables declaration//GEN-END:variables

    private void loadFile() {
        int retVal = loadChooser.showOpenDialog(this);
        
        File baseFile;
        
        if (retVal == JFileChooser.APPROVE_OPTION) {
            baseFile = loadChooser.getSelectedFile();
            try {
                inFile = PDDocument.load(baseFile);
                delPages.clear();
                outFile = null;
            } catch (IOException io) {
                addToLog("Failed to load pdf");
            }
        } else {
            addToLog("No file selected");
    }
}

    private void addToLog(String outMessage) {
        String.join("", logString, outMessage, "\n");
    }
    
    private void createOutFile() {
        int i = 0;
        if (inFile != null) {
            outFile = new PDDocument();
            for (PDPage page:inFile.getPages()) {
                if (!delPages.contains(i)) {
                    outFile.addPage(inFile.getPage(i));
                }
                i++;
            }
        } else {
            addToLog("No source file selected");
        }
    }
    
    private void saveFile() {
        int retVal = saveChooser.showOpenDialog(this);
        
        String savePath;
        
        if (retVal == JFileChooser.APPROVE_OPTION) {
            savePath = saveChooser.getSelectedFile().getAbsolutePath();
            if (outFile != null) {
                try {
                    outFile.save(savePath);
                } catch (IOException ioe) {
                    addToLog("Failed to save");
                }
            } else {
                addToLog("No outFile created (This should never happen)");
            }
        } else {
            addToLog("No save path selected");
        }
    }
    
}